AmadeusITGroup/AgnosUI

- playwright.config.ts
Just to see what are the performance impact on the test.
Anyway, to would be good to set it this way, as there is no point to record a video for passing tests. The same for the trace, data are recorded during the test even if it's removed if the test passes.
> test: Record traces and videos on retry only

- core/lib/modal/modal.ts
- react/lib/modal/Modal.tsx
This removes the need for "as any" in react.
> Better types for modal actions

- demo/svelte.config.js
Two builds from the same git commit should produce the same output.
cf https://kit.svelte.dev/docs/configuration#version
> build: deterministic sveltekit build

- demo/src/routes/[framework]/menu/SideMenu.svelte
- demo/src/routes/[framework]/menu/menu.scss
While working on the select, I noticed that adding new widgets will end with a really large menu quickly.
This PR do some changes on the sidebar:
- Reduce the padding for breakpoint > md
- Remove the background for the active element, in favor of text-primary
- Remove the blue borders for the focused element for breakpoint > md (kept for the mobile version, it seems to me more visible).
What do you think ?
> demo: menu improvements

- .github/workflows/build.yml
- demo/src/lib/stackblitz/angular/package-lock.json
- demo/src/lib/stackblitz/react/package-lock.json
- demo/src/lib/stackblitz/svelte/package-lock.json
Stackblitz, for all frameworks, is quite slow to boot / install / serve, and one of the biggest reasons of the slowness is the install step.
This can be sped up by providing a lockfile.
> feat: speed up stackblitz install

- eslint-plugin/src/svelte-check-props.ts
- eslint-plugin/test/svelte-check-props.spec.ts
- svelte/demo/samples/alert/Dynamic.route.svelte
- svelte/demo/samples/rating/Default.route.svelte
- svelte/headless/config.ts
- svelte/headless/slotTypes.ts
- svelte/headless/utils.ts
- svelte/lib/accordion/Accordion.svelte
- svelte/lib/accordion/Item.svelte
- svelte/lib/alert/Alert.svelte
- svelte/lib/modal/Modal.svelte
- svelte/lib/pagination/Pagination.svelte
- svelte/lib/rating/Rating.svelte
- svelte/lib/select/Select.svelte
- svelte/lib/slider/Slider.svelte
`createEventDispatcher` is [deprecated in Svelte 5](https://svelte-5-preview.vercel.app/docs/event-handlers), it is now recommended to use simple props.
Following #225, this PR completely removes support for on:something={...} events in AgnosUI components (in favor of only onSomething={...} as in React). This simplifies a lot the code.
> feat: removing dispatch-style events in Svelte

- demo/src/routes/+layout.svelte
While opening the landing page on mobile, scrolling to the bottom would not show the Accessibility section content.
It was due do the fact we were setting the container to height 100vh instead of 100dvh
> fix: height of scrollable content container

- .eslintrc.json
- angular/demo/src/app/samples/modal/component.route.ts
- angular/demo/src/app/samples/transition/innerComponent.component.ts
- angular/demo/src/app/utils.ts
- angular/headless/src/utils/directive.ts
- angular/headless/src/utils/zone.ts
- code-coverage/lib/vitestProvider.ts
- core/src/components/modal/modal.spec.ts
- core/src/services/transitions/baseTransitions.spec.ts
- core/src/services/transitions/cssTransitions.spec.ts
- core/src/services/transitions/simpleClassTransition.spec.ts
- core/src/utils/internal/promise.spec.ts
- demo/src/lib/layout/Sample.svelte
- demo/src/routes/+layout.svelte
- demo/src/service-worker.ts
- e2e/fixture.ts
- e2e/floatingUI/floatingUI.e2e-spec.ts
- react/demo/src/app/samples/transition/InnerComponent.tsx
- svelte/demo/src/app/samples/transition/InnerComponent.svelte
The PR does not pass yet, this is just to discuss about it first.
It enables two rules:
- https://typescript-eslint.io/rules/no-floating-promises/
- https://typescript-eslint.io/rules/no-misused-promises/
With this PR, promise need to be explicitly handled. For example:
```typescript
await getAsyncFn();
// or, if we don't want to wait:
void getAsyncFn();
```
The point is to avoid issues/mistakes in test as [here](https://github.com/AmadeusITGroup/AgnosUI/blob/ad8da0864a080db682d78e1220f9c37deadd348b/e2e/floatingUI/floatingUI.e2e-spec.ts#L13), where ```toBeVisible()``` is not awaited.
But probably having this rule enabled everywhere is safer.
> core: enable linter on Promise

- demo/vite.config.ts
Launching the Vite server in local would result in a temporary 500 error navigating from the home page to any other page.
This is due to the fact some dependencies (highlight.js, floating-ui and tansu) are needed everywhere but the home page, thus vite would not optimize the dependencies at initial startup.
This PR proposes to list those dependencies as "to always optimize".
> fix: initial 500 error when navigating from home page

- demo/src/routes/+layout.svelte
- demo/src/routes/menu/MobileSubMenu.svelte
Display lg menu + mobile 'On this page' section
Desktop / tablet landscape
Tablet portrait
Mobile
> fix: md breakpoint display

- svelte/.eslintrc.json
- svelte/demo/src/app/samples/alert/Generic.route.svelte
- svelte/demo/src/app/samples/alert/Icon.route.svelte
- svelte/demo/src/app/samples/alert/Icon.svelte
- svelte/demo/src/app/samples/modal/ComponentModal.svelte
- svelte/demo/src/app/samples/modal/StackModal.svelte
- svelte/demo/src/app/samples/pagination/CustomPages.svelte
- svelte/demo/src/app/samples/pagination/ReuseDefault.svelte
- svelte/demo/src/app/samples/progressbar/Coffee.svelte
- svelte/demo/src/app/samples/progressbar/Default.route.svelte
- svelte/demo/src/app/samples/rating/CustomStar.svelte
- svelte/demo/src/app/samples/slots/RatingReadonly.svelte
The comment lines to disable the no-unused-vars eslint rule were appearing in our Code samples.
To make the samples as readable as possible, I propose to move this disabling to the eslintrc.json config with a ignoreVars regex.
> feat: remove eslint disable from svelte samples

- demo/src/lib/markdown/Markdown.svelte
based from this comment:
https://github.com/pablo-abc/svelte-markdown/issues/80#issuecomment-1745004183
> fix: markdown rendering on follow-up navigation

- core/package.json
- package.json
To run the unit test in headful mode.
I had to search a little how to do it, because of the issue : https://github.com/vitest-dev/vitest/issues/5055, to use the --no-browser.headless command line. Maybe we will adapt the command once the issue is fixed.
> test; introduce npm run tdd:debug

- angular/lib/src/components/select/select.component.ts
- core/src/components/select/select.spec.ts
- core/src/components/select/select.ts
- core/src/utils/internal/dom.ts
- demo/src/routes/docs/[framework]/components/select/examples/+page.svelte
- e2e/demo.spec.ts
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/select-custom.html
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/select-default.html
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/select-playground.html
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/select-select.html
- e2e/select/select.chromium.e2e-spec.ts
- e2e/select/select.e2e-spec.ts
- e2e/utils.ts
- react/lib/src/components/select/select.tsx
- svelte/lib/src/components/select/Select.svelte
> test: add tests and fix accessibility issues for the select

- demo/vite.config.ts
We have a issue currently that can be reproduced by the following steps:
Run
```bash
git clean -dfX && npm ci && npm run build:ci && npm run dev
```
Observe the issue, delete the dist folder in the core folder, run ```npm run dev``` and observe that it's back to normal.
This PR solves this.
> fix: running local after a build

- eslint-plugin/src/svelte-check-slots.ts
- package-lock.json
- svelte/demo/src/app/samples/alert/Icon.svelte
- svelte/demo/src/app/samples/pagination/ReuseDefault.svelte
- svelte/demo/src/app/samples/slots/RatingReadonly.svelte
- svelte/demo/src/app/samples/toast/Action.svelte
- svelte/headless/package.json
- svelte/headless/src/Slot.svelte
- svelte/lib/src/components/accordion/Item.svelte
- svelte/lib/src/components/accordion/ItemDefaultStructure.svelte
- svelte/lib/src/components/alert/Alert.svelte
- svelte/lib/src/components/alert/AlertDefaultStructure.svelte
- svelte/lib/src/components/modal/Modal.svelte
- svelte/lib/src/components/modal/ModalDefaultHeader.svelte
- svelte/lib/src/components/modal/ModalDefaultStructure.svelte
- svelte/lib/src/components/pagination/Pagination.svelte
- svelte/lib/src/components/pagination/PaginationDefaultPages.svelte
- svelte/lib/src/components/pagination/PaginationDefaultStructure.svelte
- svelte/lib/src/components/progressbar/Progressbar.svelte
- svelte/lib/src/components/progressbar/ProgressbarDefaultStructure.svelte
- svelte/lib/src/components/rating/Rating.svelte
- svelte/lib/src/components/select/Select.svelte
- svelte/lib/src/components/slider/Slider.svelte
- svelte/lib/src/components/slider/SliderDefaultStructure.svelte
- svelte/lib/src/components/toast/Toast.svelte
- svelte/lib/src/components/toast/ToastDefaultStructure.svelte
This PR reverts #522 and implements the workaround mentioned in https://github.com/sveltejs/svelte/issues/9137, which is replacing:
```svelte
<MyComponent>
<slot name="otherComponentSlot" slot="myComponentSlot" let:props {...props}/>
</MyComponent>
```
by:
```svelte
<MyComponent>
<svelte:fragment slot="myComponentSlot" let:props><slot name="otherComponentSlot" {...props}/></svelte:fragment>
</MyComponent>
```
> Workaround for SSR svelte issue with slots

- angular/lib/src/components/rating/rating.component.ts
- core/package.json
- core/src/components/rating/rating.spec.ts
- core/src/components/rating/rating.ts
- core/src/types.ts
- core/src/utils/directive.spec.ts
- core/src/utils/directive.ts
- core/src/utils/internal/dom.spec.ts
- core/src/utils/internal/dom.ts
- e2e/rating/rating.e2e-spec.ts
- package-lock.json
- page-objects/lib/rating.po.ts
- react/lib/src/components/rating/rating.tsx
- svelte/lib/src/components/rating/Rating.svelte
- viteAlias.ts
fix #537
This is a POC to see what's happen if we delegate more works on directives:
- increase the common code
- decrease the code duplication between frameworks
- ease the headless usage
On the other hand:
-  bypass the framework templating  engine
> feat: refactor directives purposes

- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/alert/alert.tsx
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/select/select.tsx
- react/bootstrap/src/components/slider/slider.tsx
- react/bootstrap/src/components/toast/toast.tsx
This PR refactors some react components to avoid calling `useDirective` when the element is not in the DOM.
This is important for SSR because soon (in a future PR), `useDirective` will call `ssrAttributes` and this will call the directive on the server, and this must be skipped if the element will not be in the DOM (as it is useless and because it can cause some errors).
As it is not allowed to call a hook a variable number of times in a component, some react components had to be split in smaller components.
> refactor(react): avoid calling useDirective when element is not in the DOM

- core/src/components/accordion/accordion.ts
- core/src/utils/directive.ts
- e2e/ssr.ssr-e2e-spec.ts
- package-lock.json
- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/alert/alert.tsx
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/progressbar/progressbar.tsx
- react/bootstrap/src/components/rating/rating.tsx
- react/bootstrap/src/components/select/select.tsx
- react/bootstrap/src/components/toast/toast.tsx
- react/headless/package.json
- react/headless/src/utils/directive.ts
- react/ssr-app/tsconfig.json
- svelte/bootstrap/src/components/rating/Rating.svelte
This PR is built on top of #697 
It adds support for server-side rendering with react.
> Server-side rendering with react

- angular/bootstrap/src/agnos-ui-angular.module.ts
- angular/bootstrap/src/components/modal/modal.component.ts
- angular/bootstrap/src/components/rating/rating.component.ts
- angular/bootstrap/src/components/select/select.component.ts
- angular/bootstrap/src/components/slider/slider.component.ts
- angular/bootstrap/src/components/toast/toast.component.ts
- angular/demo/bootstrap/src/app/samples/directives/usage.route.ts
- angular/demo/bootstrap/src/app/samples/navmanager/navmanager.route.ts
- angular/demo/bootstrap/src/app/samples/navmanager/navmanagerWithSelector.route.ts
- angular/demo/bootstrap/src/app/samples/slider/coffee-slider.component.ts
- angular/demo/bootstrap/src/app/samples/slider/custom-handle.component.ts
- angular/demo/bootstrap/src/app/samples/transition/collapse.component.ts
- angular/demo/bootstrap/src/app/samples/transition/innerComponent.component.ts
- angular/docs/Directives.md
- angular/headless/src/utils/directive.ts
- core/src/types.ts
- core/src/utils/directive.spec.ts
- core/src/utils/directive.ts
- docs/01-Headless/03-Directives.md
- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/alert/alert.tsx
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/rating/rating.tsx
- react/bootstrap/src/components/select/select.tsx
- react/bootstrap/src/components/toast/toast.tsx
- react/headless/src/utils/directive.ts
This PR adds the `multiDirective` directive in the core that can take as a parameter an array of directives to apply, optionally with their parameters: `[[myDirectiveWithParam, myParam], myDirectiveWithoutParam]`.
Using this directive, it is easy to implement in all frameworks the support for multiple directives when support for only one directive is already implemented.
This PR changes the `useDirectives` hook in react to now use `multiDirective` instead of `mergeDirectives` (with a change in its signature).
This PR also changes the `[auUse]` directive in Angular to also use `multiDirective` and provide multi-directive support in Angular (this is a breaking change).
> feat: multiDirective and corresponding refactoring in react and Angular

- angular/headless/src/utils/widget.spec.ts
- angular/headless/src/utils/widget.ts
This is a breaking change: this PR removes the `@CachedProperty` decorator because it was mainly used to merge directives in a widget before using them with `auUse` (cf [this commit](https://github.com/AmadeusITGroup/AgnosUI/commit/0308b290c763da65761a0157960ddc831dca3321)), which only supports a single directive. Now that `auUseMulti` is available to apply multiple directives without requiring to merge them before, `CachedProperty` is no longer needed most of the time.
> refactor: remove useless CachedProperty

- react/headless/src/config.tsx
- react/headless/src/utils/stores.ts
- react/headless/src/utils/widget.ts
> fix(react): useObservablesProxy calls setState during a render

- core-bootstrap/vite.config.ts
This PR removes the duplication of [`@amadeus-it-group/tansu`](https://github.com/AmadeusITGroup/tansu), which can lead to strange errors (`computed` store not being recomputed when its dependencies change, because it comes from a different instance of `@amadeus-it-group/tansu`).
This currently happens in the carousel and the collapse bootstrap components (both use `@amadeus-it-group/tansu` from `@agnos-ui/core-bootstrap`).
> fix: prevent tansu from being included in the build of core-bootstrap

- demo/src/lib/stackblitz/angular-bootstrap/index.html
- demo/src/lib/stackblitz/angular-bootstrap/package-lock.json
- demo/src/lib/stackblitz/angular-bootstrap/package.json
- demo/src/lib/stackblitz/angular-bootstrap/src/main.css
- demo/src/lib/stackblitz/react-bootstrap/index.html
- demo/src/lib/stackblitz/react-bootstrap/package-lock.json
- demo/src/lib/stackblitz/react-bootstrap/package.json
- demo/src/lib/stackblitz/react-bootstrap/src/main.css
- demo/src/lib/stackblitz/svelte-bootstrap/index.html
- demo/src/lib/stackblitz/svelte-bootstrap/package-lock.json
- demo/src/lib/stackblitz/svelte-bootstrap/package.json
- demo/src/lib/stackblitz/svelte-bootstrap/src/main.css
This fixes flaky stackblitz e2e tests (caused by the CDN returning an error).
> refactor(stackblitz): install bootstrap from npm instead of using the CDN

- angular/bootstrap/ng-package.json
- angular/bootstrap/src/components/carousel/carousel.component.ts
- angular/headless/ng-package.json
The exported type of `plugins` input was:
```typescript
readonly plugins: import("@angular/core").InputSignal<import("embla-carousel").CreatePluginType<import("node_modules/embla-carousel/esm/components/Plugins").LoosePluginType, {}>[] | undefined>;
```
instead of
```typescript
readonly plugins: InputSignal<EmblaPluginType[] | undefined>;
```
> fix(angular, carousel): exported type of plugins input
