- demo/src/lib/layout/Header.svelte
- demo/src/routes/+layout.svelte
- demo/src/routes/+page.svelte
- demo/src/routes/[framework]/+layout.svelte
Making the display slightly better on mobile, by replacing the Work In Progress by an icon on small width devices + handling our menu layout better in other pages.
> fix: landing page on mobile #35

- demo/src/lib/layout/Code.svelte
- demo/src/lib/layout/Sample.svelte
- demo/src/lib/layout/playground/PlaygroundValue.svelte
- demo/src/routes/+page.svelte
- demo/src/routes/[framework]/components/alert/examples/+page.svelte
- demo/src/routes/[framework]/components/modal/examples/+page.svelte
- demo/src/routes/styles.scss
- e2e/demo.spec.ts
Enable the color contrast rule in the e2e accessibility tests.
Also added an onload function to change the iframe heights after the sample is loaded.
> Closes #33 color contrast in demo website

- demo/src/service-worker.ts
It was mistakenly removed in 4c71c4a905c5b52564f59233d05367a0ba91b855 (#82)
> fix: adding back the service worker

- svelte/lib/slot/slot.ts
Another part of the fix has to be done on Svelte side, cf https://github.com/sveltejs/svelte/issues/9137
> fix(svelte): partly fixes SSR with svelte

- demo/scripts/includeSamples.plugin.ts
This PR implements what I was suggesting [here](https://github.com/AmadeusITGroup/AgnosUI/pull/123#discussion_r1322746948)
> refactor(demo): transform sample source code at compile time

- core/lib/slider.ts
Just to avoid to call `storeName$()` multiple time in computed.
> Slider: optimize store subscriber calls

- angular/lib/src/lib/slider/slider.component.ts
- core/lib/slider.spec.ts
- core/lib/slider.ts
- e2e/demo.spec.ts
- e2e/samplesMarkup.e2e-spec.ts-snapshots/slider-default.html
- e2e/samplesMarkup.e2e-spec.ts-snapshots/slider-playground.html
- e2e/samplesMarkup.e2e-spec.ts-snapshots/slider-range.html
- e2e/samplesMarkup.e2e-spec.ts-snapshots/slider-vertical.html
- e2e/slider/slider.e2e-spec.ts
- page-objects/lib/slider.po.ts
- react/lib/Slider.tsx
- svelte/lib/slider/Slider.svelte
Add the aria-label for the handles via a prop.
This PR re-activate the axe tests for the slider (which failed without it).
> Slider: aria-label for the handles

- core/lib/services/writables.spec.ts
- core/lib/services/writables.ts
- core/lib/slider.spec.ts
- core/lib/slider.ts
and add some options to the `typeNumberInRangeFactory` utility.
> Slider: don't accept 0 for the step

- demo/src/lib/stackblitz/angular/index.html
- demo/src/lib/stackblitz/react/index.html
- demo/src/lib/stackblitz/svelte/index.html
Small PR to align the Bootstrap version of Stackblitz on the dev one.
> Boostrap upgrade for Stackblitz

- e2e/slider/slider.e2e-spec.ts
Just to avoid https://github.com/AmadeusITGroup/AgnosUI/pull/271/files#file-e2e-slider-slider-e2e-spec-ts-L243
> Slider: more stable tests

- e2e/floatingUI/floatingUI.e2e-spec.ts
Commit https://github.com/AmadeusITGroup/AgnosUI/commit/60bbb4a2a41958f6929fe6d162283ff75f8d2bf7 was integrated without
rebase and tests failed because they were not adapted after the change in
https://github.com/AmadeusITGroup/AgnosUI/commit/570275bbf0a516d45f2adeca0761277b41520eb4.
> fix: fixing e2e tests

- e2e/slider/slider.e2e-spec.ts
cf flaky test in https://github.com/AmadeusITGroup/AgnosUI/pull/309/files
> fix: slider e2e test stability and readability improvement

- angular/demo/src/app/samples/select/default.route.ts
- angular/lib/src/select/select.component.ts
- core/src/components/select/select.spec.ts
- core/src/components/select/select.ts
- core/src/services/floatingUI.ts
- demo/src/routes/[framework]/components/select/examples/+page.svelte
- e2e/samplesMarkup.e2e-spec.ts
- e2e/samplesMarkup.e2e-spec.ts-snapshots/select-default.html
- react/demo/src/app/samples/select/Default.route.tsx
- react/lib/src/Select.tsx
- svelte/demo/src/app/samples/select/Default.route.svelte
- svelte/lib/src/select/Select.svelte
Enables floating UI positioning.
fix #190
> feat(select): positioning

- e2e/slider/slider.e2e-spec.ts
cf flaky test in https://github.com/AmadeusITGroup/AgnosUI/pull/308/files
> fix: slider e2e test stability

- demo/src/lib/layout/Header.svelte
- demo/src/routes/[framework]/getting-started/installation/+page.svelte
- demo/src/routes/[framework]/menu/SideMenu.svelte
In this way, it is easier to understand that the framework selected is global for your documentation
> feat: move the framework selection into the side menu

- demo/src/lib/layout/Sample.svelte
- demo/src/lib/stores.ts
- demo/src/routes/+layout.svelte
- demo/src/routes/blog/+layout.server.ts
- demo/src/routes/menu/MobileDialog.svelte
- demo/src/routes/menu/MobileMenu.svelte
- demo/src/routes/menu/MobileSubMenu.svelte
- demo/vite.config.ts
> feat: main mobile menu

- angular/lib/src/components/slider/slider.component.ts
- core/src/components/slider/slider.ts
- react/lib/src/components/slider/slider.tsx
- svelte/lib/src/components/slider/Slider.svelte
Touch testing is not implemented by Playwright and the unit testing would be not efficient in this case as the methods used are already tested.
> feat(slider): Add touch events to slider

- demo/src/lib/markdown/renderers/MdImage.svelte
- demo/src/routes/+layout.svelte
- demo/src/routes/menu/menu.scss
> fix(responsiveness): Main content / menu sizes

- docs/services/02-floating-ui.md
> docs: floating UI documentation

- demo/src/routes/menu/CollapsibleSection.svelte
- demo/src/routes/menu/MobileDialog.svelte
- demo/src/routes/menu/SideMenu.svelte
- demo/src/routes/menu/menu.scss
> feat(menu): Add collapsible sections to side menu

- angular/demo/src/app/samples/directives/usage.route.ts
- angular/docs/Directives.md
- common/samples/directives/sample-directive.ts
- demo/src/lib/markdown/samples.ts
- docs/01-Headless/03-Directives.md
- e2e/samplesMarkup.e2e-spec.ts-snapshots/directives-usage.html
- react/demo/src/app/samples/directives/Usage.route.tsx
- react/docs/Directives.md
- svelte/demo/src/app/samples/directives/Usage.route.svelte
- svelte/docs/Directives.md
> docs: Directives

- style-bootstrap/scss/_slider.scss
- style-bootstrap/scss/_variables.scss
Bug in the font weight of the label now, added font-weight for label + used calc for margins
> fix(slider): style bootstrap font-weight + margin

- demo/src/app.html
- demo/src/routes/+layout.svelte
> feat: release the website into the wild

- angular/demo/src/app/samples/select/custom.route.ts
- angular/lib/src/components/select/select.component.ts
- core/src/components/select/select.spec.ts
- core/src/components/select/select.ts
- core/src/services/navManager.spec.ts
- core/src/services/navManager.ts
- core/src/utils/directive.ts
- core/src/utils/internal/dom.ts
- core/src/utils/internal/isFocusable.ts
- e2e/samplesMarkup.e2e-spec.ts-snapshots/select-default.html
- e2e/select/har/02bff8387300d63552c898874f230b7a33e12e06.json
- e2e/select/har/wikipedia.har
- e2e/select/select.e2e-spec.ts
- react/demo/src/app/samples/select/Custom.route.tsx
- react/lib/src/components/select/select.tsx
- svelte/demo/src/app/samples/select/Custom.route.svelte
- svelte/lib/src/components/select/Select.svelte
> feat(select) Keyboard navigation

- demo/package.json
- demo/src/lib/layout/Code.svelte
- demo/src/lib/layout/code.scss
- demo/src/lib/layout/dark-plus.json
- demo/src/lib/layout/highlight.ts
- demo/src/lib/layout/light-plus.json
- demo/src/lib/server/index.ts
- demo/src/lib/tooltip/Tooltip.svelte
- demo/src/lib/tooltip/tooltip.ts
- demo/src/routes/styles.scss
- demo/vite.config.ts
- package-lock.json
> feat: use shiki as highlighter

- demo/src/lib/components-metadata.ts
- demo/src/lib/layout/Header.svelte
- demo/src/lib/server/index.ts
- demo/src/routes/docs/[framework]/+layout.server.ts
- demo/src/routes/docs/[framework]/components/+layout.svelte
- demo/src/routes/docs/[framework]/components/accordion/+layout.server.ts
- demo/src/routes/docs/[framework]/components/alert/+layout.server.ts
- demo/src/routes/docs/[framework]/components/modal/+layout.server.ts
- demo/src/routes/docs/[framework]/components/pagination/+layout.server.ts
- demo/src/routes/docs/[framework]/components/progressbar/+layout.server.ts
- demo/src/routes/docs/[framework]/components/rating/+layout.server.ts
- demo/src/routes/docs/[framework]/components/select/+layout.server.ts
- demo/src/routes/docs/[framework]/components/slider/+layout.server.ts
- demo/src/routes/menu/SideMenu.svelte
> feat: status of a component, used to tag components and display badges

- core/src/components/pagination/pagination.spec.ts
- core/src/components/pagination/pagination.ts
- core/src/components/rating/rating.spec.ts
- core/src/components/rating/rating.ts
- core/src/components/select/select.spec.ts
- core/src/components/select/select.ts
- core/src/components/slider/slider.ts
- core/src/utils/stores.spec.ts
- core/src/utils/stores.ts
This PR makes the rating consistent with the progressbar (especially when inconsistent maxValue and value are provided).
> refactor: new bindableProp replacing bindableDerived in several places

- angular/demo/src/app/samples/pagination/hash.route.ts
- angular/lib/src/components/pagination/pagination.component.ts
- core/src/components/pagination/pagination.spec.ts
- core/src/components/pagination/pagination.ts
- core/src/services/hash.ts
- demo/src/routes/docs/[framework]/components/pagination/examples/+page.svelte
- e2e/pagination/pagination.e2e-spec.ts
- e2e/samplesMarkup.e2e-spec.ts-snapshots/pagination-hash.html
- page-objects/lib/pagination.po.ts
- react/demo/src/app/samples/pagination/Hash.route.tsx
- react/lib/src/components/pagination/pageItem.tsx
- react/lib/src/components/pagination/pagination.tsx
- svelte/demo/src/app/samples/pagination/Hash.route.svelte
- svelte/demo/src/common/AppCommon.svelte
- svelte/lib/src/components/pagination/Pagination.svelte
- svelte/lib/src/components/pagination/PaginationDefaultPages.svelte
> feat: pagination hrefs factory function

- angular/demo/package.json
- angular/headless/package.json
- angular/lib/package.json
- core/package.json
- package-lock.json
- react/headless/package.json
- react/lib/package.json
- svelte/headless/package.json
- svelte/lib/package.json
> feat: set tansu as peer dependency

- .github/workflows/build.yml
- demo/src/lib/stackblitz/angular/angular.json
- demo/src/lib/stackblitz/angular/index.html
- demo/src/lib/stackblitz/angular/package-lock.json
- demo/src/lib/stackblitz/angular/package.json
- demo/src/lib/stackblitz/angular/src/main.css
- demo/src/lib/stackblitz/index.ts
- demo/src/lib/stackblitz/react/index.html
- demo/src/lib/stackblitz/react/package-lock.json
- demo/src/lib/stackblitz/react/package.json
- demo/src/lib/stackblitz/react/src/main.css
- demo/src/lib/stackblitz/svelte-tailwind/index.html
- demo/src/lib/stackblitz/svelte-tailwind/package-lock.json
- demo/src/lib/stackblitz/svelte-tailwind/package.json
- demo/src/lib/stackblitz/svelte-tailwind/postcss.config.js
- demo/src/lib/stackblitz/svelte-tailwind/src/main.css
- demo/src/lib/stackblitz/svelte-tailwind/src/vite-env.d.ts
- demo/src/lib/stackblitz/svelte-tailwind/svelte.config.js
- demo/src/lib/stackblitz/svelte-tailwind/tailwind.config.js
- demo/src/lib/stackblitz/svelte-tailwind/tsconfig.json
- demo/src/lib/stackblitz/svelte-tailwind/vite.config.ts
- demo/src/lib/stackblitz/svelte/src/main.css
> feat: simplify stackblitz repos

- angular/lib/src/components/slider/slider.component.ts
- common/propsValues.ts
- core/src/components/slider/slider.spec.ts
- core/src/components/slider/slider.ts
- demo/src/routes/docs/[framework]/components/slider/playground/+page.svelte
- e2e/slider/slider.e2e-spec.ts
- page-objects/lib/slider.po.ts
- react/lib/src/components/slider/slider.tsx
- svelte/lib/src/components/slider/Slider.svelte
> feat(slider): Handle aria-valuetext customizability

- package-lock.json
- svelte/headless/package.json
- svelte/headless/src/Slot.svelte
Far from being ideal of course, but this is an attempt to work around  https://github.com/sveltejs/svelte/issues/9137.
> fix: workaround for Svelte SSR generation

- angular/demo/src/app/samples/accordion/customHeaders.route.ts
- angular/lib/src/components/accordion/accordion.component.ts
- core/src/components/accordion/accordion.spec.ts
- core/src/components/accordion/accordion.ts
- react/demo/src/app/samples/accordion/CustomHeaders.route.tsx
- react/lib/src/components/accordion/accordion.tsx
- svelte/demo/src/app/samples/accordion/CustomHeaders.route.svelte
- svelte/lib/src/components/accordion/ItemDefaultStructure.svelte
> feat(Accordion): use clear naming closes #160

- demo/src/lib/stackblitz/svelte-tailwind/package-lock.json
- demo/src/lib/stackblitz/svelte-tailwind/package.json
- demo/src/lib/stackblitz/svelte-tailwind/tailwind.config.js
- demo/src/routes/docs/[framework]/components/pagination/headless/+page.svelte
- package-lock.json
- svelte/demo/package.json
- svelte/demo/src/app-tailwind/App.svelte
- svelte/demo/src/app-tailwind/index.html
- svelte/demo/src/app-tailwind/samples/pagination/Pagination.svelte
- svelte/demo/src/app-tailwind/samples/pagination/Tailwind.route.svelte
- svelte/demo/tailwind.config.js
> feat: add dark mode and dasyUI pagination closes #521

- angular/demo/src/app/samples/slider/coffee-slider.component.ts
- angular/demo/src/app/samples/slider/custom-handle.component.ts
- angular/demo/src/app/samples/slider/custom.route.ts
- angular/demo/src/app/samples/slider/fullCustom.route.ts
- angular/headless/src/components/slider/slider.ts
- angular/lib/src/agnos-ui-angular.module.ts
- angular/lib/src/components/slider/slider.component.ts
- common/samples/slider/custom.scss
- core/src/components/slider/slider.spec.ts
- core/src/components/slider/slider.ts
- demo/src/routes/docs/[framework]/components/slider/examples/+page.svelte
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/slider-custom.html
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/slider-fullcustom.html
- react/demo/src/app/samples/slider/CoffeeSlider.tsx
- react/demo/src/app/samples/slider/Custom.route.tsx
- react/demo/src/app/samples/slider/CustomHandle.tsx
- react/demo/src/app/samples/slider/FullCustom.route.tsx
- react/headless/src/components/slider/slider.ts
- react/lib/src/components/slider/slider.tsx
- svelte/demo/src/app/samples/slider/CoffeeSlider.svelte
- svelte/demo/src/app/samples/slider/Custom.route.svelte
- svelte/demo/src/app/samples/slider/CustomHandle.svelte
- svelte/demo/src/app/samples/slider/FullCustom.route.svelte
- svelte/headless/src/components/slider/slider.ts
- svelte/lib/src/components/slider/Slider.svelte
- svelte/lib/src/components/slider/SliderDefaultHandle.svelte
- svelte/lib/src/components/slider/SliderDefaultStructure.svelte
> feat: add slots to slider

- core/src/components/accordion/accordion.ts
> feat(Accordion): use common id generator closes #508

- demo/src/lib/layout/StatusAlert.svelte
- demo/src/routes/docs/[framework]/components/+layout.svelte
> feat(Demo): Add alert for beta/progress components closes #531

- angular/lib/src/agnos-ui-angular.module.ts
- angular/lib/src/components/pagination/pagination.component.ts
- core/src/components/pagination/pagination.spec.ts
- core/src/components/pagination/pagination.ts
- react/lib/src/components/pagination/pagination.tsx
- svelte/demo/src/app/samples/pagination/ReuseDefault.svelte
- svelte/headless/src/components/pagination/pagination.ts
- svelte/lib/src/components/pagination/Pagination.svelte
- svelte/lib/src/components/pagination/PaginationDefaultPages.svelte
- svelte/lib/src/components/pagination/PaginationDefaultStructure.svelte
> feat(pagination): add slot structure closes #157

- common/samples/slider/custom.scss
closes #542
Mouse click now focus the button instead of SVG
> fix: custom slider handle mouse click

- demo/package.json
- demo/src/app.html
- demo/src/lib/layout/Header.svelte
- demo/src/routes/blog/2024-02-01/+page.svelte
- demo/src/routes/sitemap.xml/+server.js
- demo/static/google02f06dbb4c4cd4ec.html
- docs/04-Services/03-Transition.md
- package-lock.json
> feat: website meta tags

- angular/lib/package.json
- angular/lib/scripts/verify-module.mjs
- angular/lib/src/agnos-ui-angular.module.ts
- package.json
> ci(angular): fail build when an angular directive or component is not exported

- angular/lib/src/components/pagination/pagination.component.ts
- core/src/components/pagination/pagination.spec.ts
- core/src/components/pagination/pagination.ts
- react/lib/src/components/pagination/pagination.tsx
- svelte/lib/src/components/pagination/PaginationDefaultPages.svelte
> fix: pagination ellipsis item - a11y

- core/src/config.ts
> fix(core): unsafe merge in core

- core/src/services/floatingUI.ts
- core/src/utils/stores.ts
> fix: type guard on core component stores

- core/src/components/select/select.spec.ts
Skip flaky unit test.
Fix will be tracked with #609
> fix(test): skip flaky unit test

- angular/demo/daisyui/src/app/samples/pagination/default.route.ts
- angular/demo/daisyui/src/app/samples/rating/default.route.ts
- angular/demo/daisyui/src/app/samples/rating/rating.component.html
- angular/demo/daisyui/src/app/samples/rating/rating.component.ts
- demo/src/lib/components-metadata.ts
- demo/src/lib/server/index.ts
- demo/src/lib/stores.ts
- demo/src/routes/docs/[framework]/components/accordion/+layout.server.ts
- demo/src/routes/docs/[framework]/components/pagination/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/+layout.svelte
- demo/src/routes/docs/[framework]/daisyUI/pagination/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/pagination/headless/+page.svelte
- demo/src/routes/docs/[framework]/daisyUI/rating/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/rating/headless/+page.svelte
- docs/01-Headless/04-Implementation.md
- docs/02-DaisyUI/doc.md
- package-lock.json
- package.json
- react/demo/src/daisyui/samples/pagination/Default.route.tsx
- react/demo/src/daisyui/samples/rating/Default.route.tsx
- react/demo/src/daisyui/samples/rating/Rating.tsx
- svelte/demo/src/daisyui/samples/pagination/Default.route.svelte
- svelte/demo/src/daisyui/samples/rating/Default.route.svelte
- svelte/demo/src/daisyui/samples/rating/Rating.svelte
> feat(rating): headless daisyUI ex

- angular/lib/src/components/progressbar/progressbar.component.ts
- core/src/components/components.spec-utils.ts
- core/src/components/progressbar/progressbar.spec.ts
- core/src/components/progressbar/progressbar.ts
- core/src/components/rating/rating.spec.ts
- core/tsconfig.json
- react/lib/src/components/progressbar/progressbar.tsx
- svelte/lib/src/components/progressbar/Progressbar.svelte
> Refactor progressbar to use core directives

- angular/demo/daisyui/src/app/samples/progressbar/default.route.ts
- angular/demo/daisyui/src/app/samples/progressbar/progressbar.component.ts
- angular/demo/daisyui/src/app/samples/progressbar/radial-progress.component.ts
- demo/src/lib/components-metadata.ts
- demo/src/lib/server/index.ts
- demo/src/routes/docs/[framework]/daisyUI/pagination/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/progressbar/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/progressbar/headless/+page.svelte
- demo/src/routes/docs/[framework]/daisyUI/rating/+layout.server.ts
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/daisyui-progressbar-default.html
- react/demo/src/daisyui/samples/progressbar/Default.route.tsx
- react/demo/src/daisyui/samples/progressbar/Progressbar.tsx
- react/demo/src/daisyui/samples/progressbar/RadialProgress.tsx
- svelte/demo/src/daisyui/samples/progressbar/Default.route.svelte
- svelte/demo/src/daisyui/samples/progressbar/Progressbar.svelte
- svelte/demo/src/daisyui/samples/progressbar/RadialProgress.svelte
> Progressbar daisyui

- angular/demo/bootstrap/src/app/samples/slider/coffee-slider.component.ts
- angular/demo/bootstrap/src/app/samples/slider/custom-handle.component.ts
- angular/lib/src/components/slider/slider.component.ts
- common/samples/slider/custom.scss
- core/src/components/slider/slider.ts
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/bootstrap-slider-custom.html
- e2e/samplesMarkup.chromium.e2e-spec.ts-snapshots/bootstrap-slider-fullcustom.html
- react/demo/src/bootstrap/samples/slider/CoffeeSlider.tsx
- react/demo/src/bootstrap/samples/slider/CustomHandle.tsx
- react/lib/src/components/slider/slider.tsx
- svelte/demo/src/bootstrap/samples/slider/CoffeeSlider.svelte
- svelte/demo/src/bootstrap/samples/slider/CustomHandle.svelte
- svelte/lib/src/components/slider/Slider.svelte
- svelte/lib/src/components/slider/SliderDefaultHandle.svelte
- svelte/lib/src/components/slider/SliderDefaultStructure.svelte
> feat(slider): Refactor using attributes directives

- angular/demo/daisyui/src/app/samples/slider/default.route.ts
- angular/demo/daisyui/src/app/samples/slider/slider.component.html
- angular/demo/daisyui/src/app/samples/slider/slider.component.ts
- core/src/components/slider/slider.ts
- demo/src/lib/components-metadata.ts
- demo/src/lib/server/index.ts
- demo/src/routes/docs/[framework]/components/accordion/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/rating/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/slider/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/slider/headless/+page.svelte
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/daisyui-slider-default.html
- react/demo/src/daisyui/samples/slider/Default.route.tsx
- react/demo/src/daisyui/samples/slider/Slider.tsx
- svelte/demo/src/daisyui/samples/slider/Default.route.svelte
- svelte/demo/src/daisyui/samples/slider/Slider.svelte
> feat(slider): Implement daisyUI example

- core/src/components/slider/slider.ts
> fix(slider): handle touchstart becomes an active element

- angular/demo/bootstrap/src/app/samples/accordion/customHeaders.route.ts
- angular/lib/src/components/accordion/accordion.component.ts
- core/src/components/accordion/accordion.spec.ts
- core/src/components/accordion/accordion.ts
- e2e/accordion/accordion.e2e-spec.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-accordion-customheaders.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-accordion-default.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-accordion-playground.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-accordion-togglepanels.html
- page-objects/lib/accordion.po.ts
- react/demo/src/bootstrap/samples/accordion/CustomHeaders.route.tsx
- react/lib/src/components/accordion/accordion.tsx
- svelte/demo/src/bootstrap/samples/accordion/CustomHeaders.route.svelte
- svelte/lib/src/components/accordion/Accordion.svelte
- svelte/lib/src/components/accordion/Item.svelte
- svelte/lib/src/components/accordion/ItemDefaultStructure.svelte
> feat(accordion): directive implementation

- .github/workflows/e2e-tests.yml
- e2e/fixture.ts
- e2e/global-setup.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts
- e2e/serverManager.ts
- e2e/types.ts
- package-lock.json
- package.json
- playwright.config.ts
Note that this change is also a workaround for:
https://github.com/microsoft/playwright/issues/18209
> refactor(e2e): only start servers when needed

- core/src/components/pagination/pagination.ts
- core/src/components/rating/rating.ts
- core/src/components/select/select.ts
- core/src/components/slider/slider.ts
- demo/package.json
- demo/src/lib/layout/Code.svelte
- demo/src/lib/layout/doc/ApiDoc.svelte
- demo/src/lib/layout/doc/DocSection.svelte
- demo/src/routes/docs/[framework]/components/accordion/api/+page.svelte
- demo/src/routes/docs/[framework]/components/alert/api/+page.svelte
- demo/src/routes/docs/[framework]/components/modal/api/+page.svelte
- demo/src/routes/docs/[framework]/components/pagination/api/+page.svelte
- demo/src/routes/docs/[framework]/components/progressbar/api/+page.svelte
- demo/src/routes/docs/[framework]/components/rating/api/+page.svelte
- demo/src/routes/docs/[framework]/components/select/api/+page.svelte
- demo/src/routes/docs/[framework]/components/slider/api/+page.svelte
- demo/src/routes/docs/[framework]/components/toast/api/+page.svelte
- scripts/doc/api-doc.ts
> fix(alert, toast, doc): default values in api doc for alert and toast

- core/src/utils/directive.ts
> fix: dynamic iframe resizing in demo

- angular/demo/daisyui/src/app/samples/alert/alert.component.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/daisyui-alert-default.html
- react/bootstrap/src/components/alert/alert.tsx
- react/demo/src/daisyui/samples/alert/Alert.tsx
- svelte/bootstrap/src/components/alert/Alert.svelte
- svelte/demo/src/daisyui/samples/alert/Alert.svelte
> feat(alert): implement attribute directives

- docs/01-Headless/03-Directives.md
- react/docs/Directives.md
- svelte/docs/Directives.md
> feat: update doc of directives

- angular/bootstrap/src/components/select/select.component.ts
- core/src/components/select/select.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-select-custom.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-select-default.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-select-playground.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-select-select.html
- e2e/ssr.ssr-e2e-spec.ts-snapshots/ssr.html
- react/bootstrap/src/components/select/select.tsx
- svelte/bootstrap/src/components/select/Select.svelte
> feat(select): Refactor using directives

- angular/demo/daisyui/src/app/samples/rating/rating.component.html
- e2e/htmlSnapshot.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/daisyui-rating-default.html
- react/demo/src/daisyui/samples/rating/Rating.tsx
- svelte/demo/src/daisyui/samples/pagination/Pagination.svelte
- svelte/demo/src/daisyui/samples/progressbar/RadialProgress.svelte
- svelte/demo/src/daisyui/samples/rating/Rating.svelte
> feat: consistent markup for DaisyUI rating sample

- demo/src/lib/layout/playground/Playground.svelte
> feat: in construction warning for playground tab

- angular/demo/bootstrap/src/app/samples/modal/default.route.ts
- angular/demo/daisyui/src/app/samples/modal/default.route.ts
- angular/demo/daisyui/src/app/samples/modal/modal.component.ts
- angular/demo/daisyui/src/app/samples/modal/modal.service.ts
- core-bootstrap/src/components/modal/modal.ts
- core/src/components/modal/modal.ts
- core/src/config.ts
- demo/src/lib/components-metadata.ts
- demo/src/lib/server/index.ts
- demo/src/routes/docs/[framework]/daisyUI/alert/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/modal/+layout.server.ts
- demo/src/routes/docs/[framework]/daisyUI/modal/api/+page.svelte
- demo/src/routes/docs/[framework]/daisyUI/modal/headless/+page.svelte
- demo/src/routes/docs/[framework]/daisyUI/pagination/+layout.server.ts
- e2e/demo-po/modal.po.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-modal-default.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/daisyui-modal-default.html
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/pagination/pagination.tsx
- react/demo/src/bootstrap/samples/modal/Default.route.tsx
- react/demo/src/daisyui/samples/modal/Default.route.tsx
- react/demo/src/daisyui/samples/modal/Modal.tsx
- svelte/demo/src/bootstrap/samples/modal/Default.route.svelte
- svelte/demo/src/daisyui/samples/modal/Default.route.svelte
- svelte/demo/src/daisyui/samples/modal/Modal.svelte
> feat: headless modal sample

- scripts/bootstrapTypes/genTypeExports.ts
As mentioned [here](https://github.com/AmadeusITGroup/AgnosUI/pull/801#pullrequestreview-2118588965) I am opening this PR to simplify the logic to generate type imports in `genTypeExports.ts`
> refactor: simplify logic to generate type imports in genTypeExports

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- DEVELOPER.md
- README.md
> feat: pr template and contributing

- .github/workflows/build.yml
- .github/workflows/e2e-tests.yml
oidc does not work on PR from a fork (issue: https://github.com/codecov/codecov-action/issues/1594)
> chore(codecov): fixing an issue on release 4.6.0 action codecov

- angular/bootstrap/src/config.ts
- angular/headless/src/utils/widget.spec.ts
- angular/headless/src/utils/widget.ts
- core-bootstrap/src/components/accordion/accordion.ts
- core-bootstrap/src/components/alert/alert.ts
- core-bootstrap/src/components/collapse/collapse.ts
- core-bootstrap/src/components/modal/modal.ts
- core-bootstrap/src/components/pagination/pagination.ts
- core-bootstrap/src/components/progressbar/progressbar.ts
- core-bootstrap/src/components/rating/rating.ts
- core-bootstrap/src/components/select/select.ts
- core-bootstrap/src/components/slider/slider.ts
- core-bootstrap/src/components/toast/toast.ts
- core/src/components/accordion/accordion.ts
- core/src/components/alert/alert.ts
- core/src/components/alert/common.ts
- core/src/components/modal/modal.ts
- core/src/components/pagination/pagination.ts
- core/src/components/progressbar/progressbar.ts
- core/src/components/rating/rating.ts
- core/src/components/select/select.ts
- core/src/components/slider/slider.ts
- core/src/components/toast/toast.ts
- core/src/services/extendWidget.spec.ts
- core/src/services/extendWidget.ts
- core/src/services/floatingUI.ts
- core/src/services/transitions/baseTransitions.ts
- core/src/types.ts
- docs/01-Headless/00-Introduction.md
- react/bootstrap/src/config.ts
Thank you for contributing to AgnosUI!
> feat: bye bye actions

- .github/workflows/renovate.yml
- renovate.json
> fix: renovate warnings

- angular/bootstrap/src/components/modal/modal.service.ts
- angular/headless/src/types.ts
- angular/headless/src/utils/widget.ts
- core/src/components/components.spec-utils.ts
- core/src/components/select/select.ts
- core/src/services/floatingUI.ts
- core/src/types.ts
- core/src/utils/internal/checks.ts
- core/src/utils/internal/promise.ts
- eslint.config.js
- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/pagination/pagination.tsx
- react/bootstrap/src/components/progressbar/progressbar.tsx
- react/bootstrap/src/components/rating/rating.tsx
- react/bootstrap/src/components/select/select.tsx
- react/bootstrap/src/components/slider/slider.tsx
- react/bootstrap/src/components/toast/toast.tsx
- react/headless/src/utils/directive.ts
- svelte/bootstrap/src/components/accordion/accordion.ts
- svelte/bootstrap/src/components/modal/modalService.ts
> feat: stricter jsdoc eslint rules

- e2e/demo.demo-e2e-spec.ts
- e2e/fixture.ts
- e2e/focustrack/focustrack.e2e-spec.ts
- e2e/rating/rating.e2e-spec.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts
- e2e/slider/slider.e2e-spec.ts
- e2e/transition/transition.e2e-spec.ts
- eslint.config.js
- package-lock.json
- package.json
- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/alert/alert.tsx
- react/bootstrap/src/components/collapse/collapse.tsx
- react/bootstrap/src/components/modal/modal.tsx
- react/bootstrap/src/components/toast/toast.tsx
- react/demo/src/bootstrap/samples/accordion/CustomHeaders.route.tsx
- react/demo/src/bootstrap/samples/focustrack/Focustrack.route.tsx
- react/demo/src/bootstrap/samples/pagination/Hash.route.tsx
- react/demo/src/bootstrap/samples/select/Custom.route.tsx
- react/demo/src/bootstrap/samples/select/Default.route.tsx
- react/demo/src/bootstrap/samples/select/Select.route.tsx
- react/demo/src/daisyui/samples/accordion/Accordion.tsx
- react/headless/src/config.tsx
> feat: setup and fix rules from eslint-plugin-react-hooks

- demo/src/routes/+page.svelte
Thank you for contributing to AgnosUI!
> docs(landingpage): update test card on landing page

- angular/bootstrap/src/components/tree/tree.component.ts
- core-bootstrap/src/scss/_variables.scss
- core-bootstrap/src/scss/tree.scss
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-tree-basic.html
- e2e/ssr.ssr-e2e-spec.ts-snapshots/ssr.html
- react/bootstrap/src/components/tree/tree.tsx
- svelte/bootstrap/src/components/tree/TreeDefaultItemToggle.svelte
Thank you for contributing to AgnosUI!
> fix(tree): Center toggle icon with flex and not after

- demo/package.json
- demo/src/app.html
- demo/src/lib/docsearch/Search.svelte
- demo/src/routes/+layout.svelte
- demo/src/routes/styles.scss
- package-lock.json
Api key is hardcoded as visible publicly in the website and used in all api call in plain text.
> feat: add docsearch

- core-bootstrap/src/components/collapse/collapse.ts
- e2e/collapse/collapse.e2e-spec.ts
- e2e/demo-po/collapse.po.ts
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-collapse-default.html
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-collapse-playground.html
- page-objects/lib/collapse.po.ts
- page-objects/lib/index.ts
> feat(collapse): add PO, e2e tests and au-collapse class

- react/bootstrap/src/components/accordion/accordion.tsx
- react/bootstrap/src/components/collapse/collapse.tsx
- react/demo/src/daisyui/samples/accordion/Accordion.tsx
- svelte/bootstrap/src/components/accordion/Item.svelte
- svelte/bootstrap/src/components/collapse/Collapse.svelte
- svelte/demo/src/daisyui/samples/accordion/AccordionItem.svelte
> feat: fwk id for accordion item and collapse

- angular/bootstrap/src/components/slider/slider.component.ts
- angular/demo/bootstrap/src/app/samples/slider/rangeLimits.route.ts
- core/src/components/slider/slider-utils.spec.ts
- core/src/components/slider/slider-utils.ts
- core/src/components/slider/slider.spec.ts
- core/src/components/slider/slider.ts
- core/src/utils/internal/dom.spec.ts
- demo/src/routes/docs/[framework]/components/slider/examples/+page.svelte
- e2e/samplesMarkup.singlebrowser-e2e-spec.ts-snapshots/bootstrap-slider-rangelimits.html
- react/demo/src/bootstrap/samples/slider/RangeLimits.route.tsx
- svelte/demo/src/bootstrap/samples/slider/RangeLimits.route.svelte
> feat(slider): range limits
